import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, Share2, FileText, Table, Copy, Check, ChevronDown, FileDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { Profile, Course, toGPA } from '@/hooks/useCalculatorState';
import jsPDF from 'jspdf';

interface ExportShareProps {
  profile: Profile | undefined;
  overallGPA: number;
  totalCredits: number;
  calculateCourseGPA: (course: Course) => { percentage: number; gpa: number };
}

const ExportShare = ({ profile, overallGPA, totalCredits, calculateCourseGPA }: ExportShareProps) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!profile) return null;

  const generateCSV = () => {
    const headers = ['Course Name', 'Credits', 'Score (%)', 'GPA', 'Assignments'];
    const rows = profile.courses.map(course => {
      const { percentage, gpa } = calculateCourseGPA(course);
      const assignments = course.assignments
        .map(a => `${a.name}: ${a.grade ?? 'N/A'}% (${a.weight}%)`)
        .join('; ');
      return [
        course.name || 'Unnamed',
        course.credits,
        percentage.toFixed(1),
        gpa.toFixed(2),
        assignments
      ];
    });

    const summary = [
      '',
      ['Overall GPA', overallGPA.toFixed(2)],
      ['Total Credits', totalCredits],
      ['Profile', profile.name],
    ];

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
      ...summary.map(row => (Array.isArray(row) ? row.join(',') : row))
    ].join('\n');

    return csvContent;
  };

  const generateTextReport = () => {
    const divider = '═'.repeat(40);
    const lines = [
      divider,
      `  📊 GPA REPORT - ${profile.name}`,
      divider,
      '',
      `  Overall GPA: ${overallGPA.toFixed(2)}`,
      `  Total Credits: ${totalCredits}`,
      '',
      divider,
      '  COURSES',
      divider,
      '',
    ];

    profile.courses.forEach(course => {
      const { percentage, gpa } = calculateCourseGPA(course);
      lines.push(`  📚 ${course.name || 'Unnamed Course'}`);
      lines.push(`     Credits: ${course.credits} | Score: ${percentage.toFixed(1)}% | GPA: ${gpa.toFixed(2)}`);
      
      if (course.assignments.length > 0) {
        lines.push('     Assignments:');
        course.assignments.forEach(a => {
          lines.push(`       • ${a.name || 'Unnamed'}: ${a.grade ?? 'N/A'}% (Weight: ${a.weight}%)`);
        });
      }
      lines.push('');
    });

    lines.push(divider);
    lines.push('  Generated by EasyGPA');
    lines.push(divider);

    return lines.join('\n');
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`);
  };

  const handleExportCSV = () => {
    const csv = generateCSV();
    downloadFile(csv, `gpa-report-${profile.name.toLowerCase().replace(/\s+/g, '-')}.csv`, 'text/csv');
  };

  const handleExportText = () => {
    const text = generateTextReport();
    downloadFile(text, `gpa-report-${profile.name.toLowerCase().replace(/\s+/g, '-')}.txt`, 'text/plain');
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('GPA Report', pageWidth / 2, y, { align: 'center' });
    y += 10;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(profile.name, pageWidth / 2, y, { align: 'center' });
    y += 15;

    // Summary box
    doc.setFillColor(240, 240, 250);
    doc.roundedRect(15, y, pageWidth - 30, 25, 3, 3, 'F');
    y += 8;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Overall GPA: ${overallGPA.toFixed(2)}`, 25, y + 4);
    doc.text(`Total Credits: ${totalCredits}`, pageWidth - 25, y + 4, { align: 'right' });
    y += 25;

    // Courses
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Courses', 15, y);
    y += 10;

    profile.courses.forEach((course) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      const { percentage, gpa } = calculateCourseGPA(course);
      
      doc.setFillColor(248, 248, 252);
      doc.roundedRect(15, y - 5, pageWidth - 30, 18, 2, 2, 'F');
      
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(course.name || 'Unnamed Course', 20, y + 4);
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.text(`${course.credits} cr | ${percentage.toFixed(1)}% | GPA: ${gpa.toFixed(2)}`, pageWidth - 20, y + 4, { align: 'right' });
      y += 20;

      if (course.assignments.length > 0) {
        course.assignments.forEach((a) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.setFontSize(9);
          doc.setTextColor(100);
          doc.text(`• ${a.name || 'Unnamed'}: ${a.grade ?? 'N/A'}% (Weight: ${a.weight}%)`, 25, y);
          doc.setTextColor(0);
          y += 6;
        });
        y += 4;
      }
    });

    // Footer
    y += 10;
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text('Generated by EasyGPA', pageWidth / 2, y, { align: 'center' });

    doc.save(`gpa-report-${profile.name.toLowerCase().replace(/\s+/g, '-')}.pdf`);
    toast.success('PDF downloaded!');
  };

  const handleCopyToClipboard = async () => {
    const text = generateTextReport();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success('Copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  };

  const handleShare = async () => {
    const text = `My GPA: ${overallGPA.toFixed(2)} (${totalCredits} credits)\n\nCalculated with EasyGPA`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My GPA Report',
          text,
          url: window.location.origin
        });
      } catch {
        // User cancelled or share failed
      }
    } else {
      await navigator.clipboard.writeText(text);
      toast.success('Link copied to clipboard!');
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl border border-border/50 overflow-hidden"
    >
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full p-4 sm:p-6 flex items-center justify-between bg-gradient-to-r from-tertiary/10 to-primary/10 hover:from-tertiary/15 hover:to-primary/15 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-tertiary/20 flex items-center justify-center">
            <Download className="w-5 h-5 text-tertiary" />
          </div>
          <div className="text-left">
            <h3 className="font-semibold text-sm sm:text-base">Export & Share</h3>
            <p className="text-xs text-muted-foreground">Download or share your report</p>
          </div>
        </div>
        <ChevronDown className={`w-5 h-5 text-muted-foreground transition-transform ${isExpanded ? 'rotate-180' : ''}`} />
      </button>

      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <div className="p-4 sm:p-6 grid grid-cols-2 sm:grid-cols-3 gap-3">
              <Button
                variant="outline"
                onClick={handleExportPDF}
                className="flex-col h-auto py-4 gap-2 col-span-2 sm:col-span-1"
              >
                <FileDown className="w-5 h-5 text-primary" />
                <span className="text-xs">Export PDF</span>
              </Button>
              
              <Button
                variant="outline"
                onClick={handleExportCSV}
                className="flex-col h-auto py-4 gap-2"
              >
                <Table className="w-5 h-5 text-secondary" />
                <span className="text-xs">Export CSV</span>
              </Button>
              
              <Button
                variant="outline"
                onClick={handleExportText}
                className="flex-col h-auto py-4 gap-2"
              >
                <FileText className="w-5 h-5 text-tertiary" />
                <span className="text-xs">Export Text</span>
              </Button>
              
              <Button
                variant="outline"
                onClick={handleCopyToClipboard}
                className="flex-col h-auto py-4 gap-2"
              >
                {copied ? (
                  <Check className="w-5 h-5 text-primary" />
                ) : (
                  <Copy className="w-5 h-5 text-tertiary" />
                )}
                <span className="text-xs">{copied ? 'Copied!' : 'Copy Report'}</span>
              </Button>
              
              <Button
                variant="outline"
                onClick={handleShare}
                className="flex-col h-auto py-4 gap-2"
              >
                <Share2 className="w-5 h-5 text-primary" />
                <span className="text-xs">Share</span>
              </Button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export default ExportShare;
